# Generated by Django 6.0.5 on 2026-05-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='schema',
            field=models.JSONField(default=list),
        ),
    ]
