# Generated by Django 6.0.5 on 2026-05-25 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
    ]
