# Generated by Django 6.0.5 on 2026-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
