# Generated by Django 6.0.5 on 2026-05-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='requires_image',
            field=models.BooleanField(default=False),
        ),
    ]
