# Generated by Django 6.0.5 on 2026-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
